export let items = [
  {
    id: 1,
    naziv: "Pizza Margherita",
    opis: "Rajčice, Sir, tijesto",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 40,
  },
  {
    id: 2,
    naziv: "Spaghetti Bolognese",
    opis: "Meso, Umak od rajčice, Tjestenina",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 35,
  },
  {
    id: 3,
    naziv: "Chicken Caesar Salad",
    opis: "Pileće meso, Zelena salata, Caesar umak",
    type: "hrana",
    subtype: "Predjelo",
    cijena: 28,
  },
  {
    id: 4,
    naziv: "Margarita Cocktail",
    opis: "0.33",
    type: "pice",
    subtype: "Alkoholna pića",
    cijena: 12,
  },
  {
    id: 5,
    naziv: "Ginger Ale",
    opis: "Gazirani napitak s okusom đumbira",
    type: "pice",
    subtype: "Bezalkoholna pića",
    cijena: 5,
  },
  {
    id: 6,
    naziv: "Espresso",
    opis: "Mala, jaka kava",
    type: "pice",
    subtype: "Kava",
    cijena: 8,
  },
  {
    id: 7,
    naziv: "Chocolate Cake",
    opis: "Čokoladna torta sa sočnim punjenjem",
    type: "hrana",
    subtype: "Desert",
    cijena: 15,
  },
  {
    id: 8,
    naziv: "Pepperoni Pizza",
    opis: "Pepperoni, Sir, tijesto",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 45,
  },
  {
    id: 9,
    naziv: "Carbonara",
    opis: "Špek, Jaja, Parmezan, Tjestenina",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 38,
  },
  {
    id: 10,
    naziv: "Caprese Salad",
    opis: "Mozzarella, Rajčice, Bosiljak",
    type: "hrana",
    subtype: "Predjelo",
    cijena: 30,
  },
  {
    id: 11,
    naziv: "Mai Tai",
    opis: "Rum, Triple sec, Limun, Sirup",
    type: "pice",
    subtype: "Alkoholna pića",
    cijena: 14,
  },
  {
    id: 12,
    naziv: "Orange Juice",
    opis: "Svježe iscijeđeni sok od naranče",
    type: "pice",
    subtype: "Bezalkoholna pića",
    cijena: 6,
  },
  {
    id: 13,
    naziv: "Cappuccino",
    opis: "Kava s mlijekom i pjenu",
    type: "pice",
    subtype: "Kava",
    cijena: 9,
  },
  {
    id: 14,
    naziv: "Cheesecake",
    opis: "Kolač od sira s voćnim preljevom",
    type: "hrana",
    subtype: "Desert",
    cijena: 18,
  },
  {
    id: 15,
    naziv: "Vegetarian Pizza",
    opis: "Razno povrće, Sir, tijesto",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 42,
  },
  {
    id: 16,
    naziv: "Lobster Pasta",
    opis: "Jastog, Bijeli umak, Tjestenina",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 60,
  },
  {
    id: 17,
    naziv: "Bruschetta",
    opis: "Paradajz, Bosiljak, Maslinovo ulje",
    type: "hrana",
    subtype: "Predjelo",
    cijena: 25,
  },
  {
    id: 18,
    naziv: "Mojito",
    opis: "Bijeli rum, Šećer, Menta, Soda",
    type: "pice",
    subtype: "Alkoholna pića",
    cijena: 16,
  },
  {
    id: 19,
    naziv: "Iced Tea",
    opis: "Ledena čajna mješavina",
    type: "pice",
    subtype: "Bezalkoholna pića",
    cijena: 4,
  },
  {
    id: 20,
    naziv: "Macchiato",
    opis: "Kava s kapljicom mlijeka",
    type: "pice",
    subtype: "Kava",
    cijena: 7,
  },
  {
    id: 21,
    naziv: "Tiramisu",
    opis: "Klasični talijanski desert s kavom",
    type: "hrana",
    subtype: "Desert",
    cijena: 20,
  },
];

export let arhivirani = [
  {
    id: 1,
    naziv: "Pizza Margherita",
    opis: "Rajčice, Sir, tijesto",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 42,
  },
  {
    id: 2,
    naziv: "Spaghetti Bolognese",
    opis: "Meso, Umak od rajčice, Tjestenina",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 38,
  },
  {
    id: 3,
    naziv: "Chicken Caesar Salad",
    opis: "Pileće meso, Zelena salata, Caesar umak",
    type: "hrana",
    subtype: "Predjelo",
    cijena: 30,
  },
  {
    id: 4,
    naziv: "Margarita Cocktail",
    opis: "0.33",
    type: "pice",
    subtype: "Alkoholna pića",
    cijena: 15,
  },
  {
    id: 5,
    naziv: "Ginger Ale",
    opis: "Gazirani napitak s okusom đumbira",
    type: "pice",
    subtype: "Bezalkoholna pića",
    cijena: 7,
  },
  {
    id: 6,
    naziv: "Espresso",
    opis: "Mala, jaka kava",
    type: "pice",
    subtype: "Kava",
    cijena: 10,
  },
  {
    id: 7,
    naziv: "Chocolate Cake",
    opis: "Čokoladna torta sa sočnim punjenjem",
    type: "hrana",
    subtype: "Desert",
    cijena: 25,
  },
  {
    id: 8,
    naziv: "Pepperoni Pizza",
    opis: "Pepperoni, Sir, tijesto",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 48,
  },
  {
    id: 9,
    naziv: "Carbonara",
    opis: "Špek, Jaja, Parmezan, Tjestenina",
    type: "hrana",
    subtype: "Glavno jelo",
    cijena: 40,
  },
  {
    id: 10,
    naziv: "Caprese Salad",
    opis: "Mozzarella, Rajčice, Bosiljak",
    type: "hrana",
    subtype: "Predjelo",
    cijena: 32,
  },
];
export let kategorije = {
  pice: [
    "Alkoholna pića",
    "Bezalkoholna pića",
    "Gazirana Bezalkoholna pića",
    "Kava",
  ],
  hrana: ["Predjelo", "Glavno jelo", "Desert"],
  ostalo: [],
};
export let userCred = {
  username: "",
  email: "",
  password: "",
  confirm_password: "",
};

export let User = "";

export function changeUser(value) {
  User = value;
}

export function getUser() {
  return User;
}
